/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 retro4.gltf 
*/

import React, {useLayoutEffect, useRef} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";
import {Delorean} from "./Delorian";
import {useThree} from "@react-three/fiber";
import * as THREE from "three";

export function Retro4(props) {
    const group = useRef();
    window.road = group;
    const {nodes, materials, animations} = useGLTF("models/mtns.gltf");
    const {actions, mixer} = useAnimations(animations, group);
    const {height: h, width: w} = useThree((state) => state.viewport);
    useLayoutEffect(() => {
        if (props.animate) actions["Animation"]?.play();
        else actions["Animation"]?.stop();
    }, [mixer, props.animate]);
    const color = new THREE.Color("#34C4FF");
    const mtnsColor = new THREE.Color("#654efc");
    color.multiplyScalar(1.8);
    mtnsColor.multiplyScalar(1.8);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Sketchfab_model" rotation={[-1.433, 0, 0]}>
                    <group name="root">
                        <group
                            name="GLTF_SceneRootNode"
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[2, 1.47, 4.23]}
                        >
                            <group name="Roundcube003_3">
                                <mesh
                                    name="Object_6"
                                    geometry={nodes.Object_6.geometry}
                                    material={materials["Black.001"]}
                                />
                                <mesh
                                    name="Object_7"
                                    geometry={nodes.Object_7.geometry}
                                    // material={materials["Material_2.001"]}
                                >
                                    <meshPhysicalMaterial
                                        toneMapped={true}
                                        emissiveIntensity={2.5}
                                        attach="material"
                                        emissive={mtnsColor}
                                        // color={"#34C4FF"}
                                        side={THREE.DoubleSide}
                                    />
                                </mesh>
                                <mesh
                                    name="Object_8"
                                    geometry={nodes.Object_8.geometry}
                                    // material={materials["Material_2.001"]}
                                >
                                    <meshPhysicalMaterial
                                        toneMapped={true}
                                        emissiveIntensity={2.5}
                                        attach="material"
                                        emissive={mtnsColor}
                                        // color={"#34C4FF"}
                                        side={THREE.DoubleSide}
                                    />
                                </mesh>
                            </group>
                            <group name="Roundcube004_4">
                                <mesh
                                    name="Object_10"
                                    geometry={nodes.Object_10.geometry}
                                    material={materials["Black.001"]}
                                />
                                <mesh
                                    name="Object_11"
                                    geometry={nodes.Object_11.geometry}
                                >
                                    <meshPhysicalMaterial
                                        toneMapped={true}
                                        emissiveIntensity={2.7}
                                        attach="material"
                                        emissive={color}
                                        // color={"#34C4FF"}
                                        side={THREE.DoubleSide}
                                    />
                                </mesh>
                            </group>
                            <group name="Roundcube005_5">
                                <mesh
                                    name="Object_13"
                                    geometry={nodes.Object_13.geometry}
                                    material={materials["Black.001"]}
                                />
                                <mesh
                                    name="Object_14"
                                    geometry={nodes.Object_14.geometry}
                                >
                                    <meshPhysicalMaterial
                                        toneMapped={true}
                                        emissiveIntensity={2.5}
                                        attach="material"
                                        emissive={color}
                                        // color={"#34C4FF"}
                                        side={THREE.DoubleSide}
                                        wireframeLinewidth={200}
                                    />
                                </mesh>
                            </group>
                            <spotLight
                                color="#87CDE8"
                                intensity={200}
                                position={[0, 0, -8]}
                            />
                            <spotLight
                                color="#87CDE8"
                                intensity={200}
                                scale={3}
                                position={[0, 0, 0]}
                            />
                            <spotLight
                                color="#F24081"
                                intensity={70}
                                scale={1}
                                position={[-w, -1, -8]}
                            />
                            <spotLight
                                color="#F24081"
                                intensity={70}
                                scale={1}
                                position={[w, -1, -8]}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("models/mtns.gltf");

// <group ref={group} {...props} dispose={null}>
// <group name="Scene">
//   <group name="Sketchfab_model" rotation={[-1.433, 0, 0]}>
//     <group name="root">
//       <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]} scale={[2, 1.47, 4.23]}>
//         <group name="Roundcube003_3">
//           <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Black.001']} />
//           <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material_2.001']} />
//           <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material_2.001']} />
//         </group>
//         <group name="Roundcube004_4">
//           <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Black.001']} />
//           <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material_3.001']} />
//         </group>
//         <group name="Roundcube005_5">
//           <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Black.001']} />
//           <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material_4.001']} />

//         </group>
//         <spotLight color="#87CDE8" intensity={300} scale={3} position={[0, -1, -8]}/>
//         <spotLight color="#F24081" intensity={70} scale={1} position={[-w, -1, -8]}/>
//         <spotLight color="#F24081" intensity={70} scale={1} position={[w, -1, -8]}/>
//       </group>
//     </group>
//   </group>
// </group>
// </group>
