/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 delorian.gltf 
Author: Meloque (https://sketchfab.com/jellyraincoat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/delorean-time-machine-low-poly-a36c5afa1bb24e16a3adfbcf08eb9390
Title: Delorean - time machine - low poly
*/

import React, {useRef} from "react";
import {GradientTexture, Stars, useGLTF, useTexture} from "@react-three/drei";
import {useFrame, useThree} from "@react-three/fiber";
import * as THREE from "three";
import {Retro4} from "./Models/Retro4";
import {Delorean} from "./Models/Delorian";
import {Bloom, EffectComposer, Scanline} from "@react-three/postprocessing";

export function CyberSpace(props) {
    const txt = useTexture("favicon/android-chrome-512x512.png");
    const {scene} = useThree();
    const {height: h, width: w} = useThree((state) => state.viewport);

    return (
        <>
            <GradientTexture
                attach="background"
                // stops={[.42, .7,  .5]}
                // colors={['#040910', '#34C4FF', '#F24081',  ]}
                stops={[0.4, 0.9]}
                colors={["#1C0623", "#F24081"]}
                size={1024} // size is optional, default = 1024
            />
            <group position={[0, 8 * h, -600]}>
                <group position={[0, 30 * h, -1000]}>
                    <Stars
                        radius={240}
                        depth={480}
                        scale={0.2}
                        count={200}
                        factor={0.8}
                        fade
                        speed={0.6}
                    />
                </group>
                <mesh position={[0, -3, 0]}>
                    {" "}
                    {/* <Sky rayleigh={.1} turbidity={.1} azimuth={0}> */}
                    <circleGeometry attach="geometry" args={[160, 160]} />
                    <meshBasicMaterial
                        transparent={true}
                        attach="material"
                        map={txt}
                        side={THREE.DoubleSide}
                    />
                </mesh>
            </group>
            <Retro4
                position={[-8, -240, 80]}
                scale={[16, 5, 10]}
                rotation={[0.2, 0, 0]}
                animate={props.animate}
            />
            <Delorean
                scale={14}
                position={[-172, -55, -140]}
                rotation={[0.2, -Math.PI / 2, 0]}
                animate={props.animate}
            />
        </>
    );
}

useGLTF.preload("models/delorian.gltf");
